from datetime import datetime
from typing import Protocol
from uuid import UUID

from ..models import AdminUser, Entity, PaymentStatus, Transaction


class EntityRepository(Protocol):
    async def add(self, entity: Entity) -> Entity: ...

    async def get(self, entity_id: UUID) -> Entity | None: ...

    async def get_by_slug(self, slug: str) -> Entity | None: ...

    async def list(self) -> list[Entity]: ...

    async def update(self, entity: Entity) -> Entity: ...

    async def delete(self, entity_id: UUID) -> None: ...


class TransactionRepository(Protocol):
    async def add(self, transaction: Transaction) -> Transaction: ...

    async def get(self, transaction_id: UUID) -> Transaction | None: ...

    async def get_by_reference(self, reference: UUID) -> Transaction | None: ...

    async def update(self, transaction: Transaction) -> Transaction: ...

    async def search(
        self,
        *,
        entity_id: UUID | None = None,
        status: PaymentStatus | None = None,
        query: str | None = None,
        date_from: datetime | None = None,
        date_to: datetime | None = None,
        order: str = "desc",
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[list[Transaction], int]: ...

    async def stats(self, entity_id: UUID | None = None) -> dict[str, int]: ...

    async def daily_series(
        self, *, days: int = 14, entity_id: UUID | None = None
    ) -> list[dict]: ...


class AdminUserRepository(Protocol):
    async def add(self, user: AdminUser) -> AdminUser: ...

    async def get(self, user_id: UUID) -> AdminUser | None: ...

    async def get_by_email(self, email: str) -> AdminUser | None: ...

    async def list(self) -> list[AdminUser]: ...

    async def update(self, user: AdminUser) -> AdminUser: ...

    async def delete(self, user_id: UUID) -> None: ...
